# Generated by Django 3.1.3 on 2021-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
