# Generated by Django 3.1.2 on 2021-08-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='request',
            name='closing_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='core.file'),
        ),
    ]
