# Generated by Django 3.1.2 on 2021-08-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210809_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='doc',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
