# Generated by Django 3.1.7 on 2021-03-02 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('rollno', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
