# Generated by Django 3.1.7 on 2021-03-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210302_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='req',
            new_name='request',
        ),
    ]
