# Generated by Django 3.1.3 on 2021-03-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210302_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='college',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='request',
            name='college',
        ),
    ]
