# Generated by Django 3.1.3 on 2021-03-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210305_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rollno',
        ),
    ]
